'use strict';

/**
 * Generate client-side ESM code for audio fingerprinting probes.
 * Analogous to the canvas frozen_template.js but for the Web Audio API.
 */
function buildAudioFrozenBundle(input) {
  const SR = input.sampleRate || 44100;
  const DUR = input.duration || 0.5;
  const BUF_LEN = input.bufferLength || Math.ceil(SR * DUR);

  const SESS = Array.isArray(input.sessions) ? input.sessions : [];
  const NUM_SUB = input.numSubSessions || SESS.length || 1;

  const js = [
    '/* ===== AudioPrint Frozen (binary upload) ===== */',
    `const SAMPLE_RATE = ${SR};`,
    `const DURATION = ${DUR};`,
    `const BUFFER_LENGTH = ${BUF_LEN};`,
    `const SESS = ${JSON.stringify(SESS)};`,
    `const NUM_SUB = ${Math.max(1, NUM_SUB)};`,
    'let PLAN = SESS[0] || {};',
    '',

    // ===== Progress event with timing detail =====
    'function __progressTick(detail){ try{ self.dispatchEvent(new CustomEvent("ap:audio",{detail:detail||null})); }catch(e){} }',
    '',

    // ===== Adaptive concurrency limiter (same as the canvas template) =====
    'function createAdaptiveLimiter(opts = {}){',
    '  const cores = (globalThis.navigator?.hardwareConcurrency || 4);',
    '  const conf = { min:2, max:Math.min(8,cores), start:Math.min(4,cores), targetMs:opts.targetMs??1500, smooth:0.2, upStep:1, downStep:1 };',
    '  let limit = conf.start; const inflight = new Set(); let ema = null; let winCnt=0, failCnt=0;',
    '  const winSize = ()=>Math.max(8, limit*2);',
    '  function _feedback(ok,ms){ ema=(ema==null)?ms:ema*(1-conf.smooth)+ms*conf.smooth; winCnt+=1; if(!ok)failCnt+=1;',
    '    if(winCnt>=winSize()){ const fr=failCnt/winCnt;',
    '      if(fr>0.15) limit=Math.max(conf.min,limit-conf.downStep);',
    '      else if(ema<conf.targetMs&&limit<conf.max) limit=limit+conf.upStep;',
    '      else if(ema>conf.targetMs*1.6) limit=Math.max(conf.min,limit-conf.downStep);',
    '      winCnt=0;failCnt=0; } }',
    '  async function run(task){ while(inflight.size>=limit){ try{await Promise.race(inflight);}catch{} }',
    '    const p=(async()=>{ const t0=performance.now(); try{ const r=await task(); _feedback(true,performance.now()-t0); return r; }',
    '    catch(e){ _feedback(false,performance.now()-t0); throw e; }})();',
    '    inflight.add(p); p.finally(()=>inflight.delete(p)); return p; }',
    '  function waitAll(){ return Promise.allSettled([...inflight]); }',
    '  return {run,waitAll,get limit(){return limit;},get ema(){return ema;}}; }',
    '',

    // ===== Retry helper =====
    'async function __retry(fn, opts={}){ const {retries=2,delay=200}=opts;',
    '  for(let i=0;i<=retries;i++){ try{return await fn();}catch(e){ if(i>=retries)throw e; await new Promise(r=>setTimeout(r,delay)); } } }',
    '',

    // ===== Fetch-with-timeout =====
    // Native fetch has no per-request timeout — a stalled socket can hang for several',
    // minutes before the browser gives up. Wrap every upload with AbortController so',
    // a stuck batch aborts cleanly and hits our retry path instead of pinning the limiter.',
    'async function __fetchTimeout(url, opts, timeoutMs){',
    '  const ctrl = new AbortController();',
    '  const tid = setTimeout(()=>ctrl.abort(), timeoutMs||60000);',
    '  try { return await fetch(url, Object.assign({}, opts||{}, {signal: ctrl.signal})); }',
    '  finally { clearTimeout(tid); }',
    '}',
    '',

    // ===== Xorshift32 (for marker embedding) =====
    'function xorshift32(u){ u=u|0; u^=u<<13; u^=(u>>>17); u^=u<<5; return u>>>0; }',
    '',

    // ===== Audio probe: OscillatorMix =====
    'async function renderOscillatorMix(params){',
    '  const p = params.oscillatorMix;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  for(const osc of p.oscillators){',
    '    const o = ctx.createOscillator();',
    '    o.type = osc.type; o.frequency.value = +osc.frequency; o.detune.value = +osc.detune;',
    '    const g = ctx.createGain(); g.gain.value = +osc.gain;',
    '    o.connect(g).connect(ctx.destination); o.start(0);',
    '  }',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: BiquadChain =====
    'async function renderBiquadChain(params){',
    '  const p = params.biquadChain;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType; osc.frequency.value = +p.inputFreq;',
    '  let node = osc;',
    '  for(const fc of p.filters){',
    '    const f = ctx.createBiquadFilter();',
    '    f.type = fc.type; f.frequency.value = +fc.frequency; f.Q.value = +fc.Q; f.gain.value = +fc.gain;',
    '    node.connect(f); node = f;',
    '  }',
    '  node.connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: CompressorProbe =====
    'async function renderCompressorProbe(params){',
    '  const p = params.compressorProbe;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType || "sawtooth"; osc.frequency.value = +p.inputFreq;',
    '  const preGain = ctx.createGain(); preGain.gain.value = +p.inputGain;',
    '  const comp = ctx.createDynamicsCompressor();',
    '  comp.threshold.value = +p.threshold; comp.knee.value = +p.knee;',
    '  comp.ratio.value = +p.ratio; comp.attack.value = +p.attack; comp.release.value = +p.release;',
    '  osc.connect(preGain).connect(comp).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: WaveShaperProbe =====
    'async function renderWaveShaperProbe(params){',
    '  const p = params.waveShaperProbe;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType || "sine"; osc.frequency.value = +p.inputFreq;',
    '  const preGain = ctx.createGain(); preGain.gain.value = +p.preGain;',
    '  const ws = ctx.createWaveShaper(); ws.oversample = p.oversample;',
    '  // Build transfer curve from polynomial coefficients',
    '  const nSeg = p.curveSegments || 256;',
    '  const curve = new Float32Array(nSeg);',
    '  const coeffs = p.curveCoeffs || [0,1,0,0,0];',
    '  for(let i=0;i<nSeg;i++){',
    '    const x = (i/(nSeg-1))*2-1; // [-1, 1]',
    '    let y = 0, xp = 1;',
    '    for(let c=0;c<coeffs.length;c++){ y += (+coeffs[c])*xp; xp *= x; }',
    '    curve[i] = Math.max(-1, Math.min(1, y));',
    '  }',
    '  ws.curve = curve;',
    '  osc.connect(preGain).connect(ws).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: ConvolverProbe =====
    'async function renderConvolverProbe(params){',
    '  const p = params.convolverProbe;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType||"sine"; osc.frequency.value = +p.inputFreq;',
    '  // Build synthetic impulse response',
    '  const irLen = p.irLength||512;',
    '  const irBuf = ctx.createBuffer(1, irLen, SAMPLE_RATE);',
    '  const irData = irBuf.getChannelData(0);',
    '  const decay = +p.irDecay||2.0;',
    '  let seed = (p.irSeed||12345)|0;',
    '  function nextRand(){ seed^=seed<<13; seed^=seed>>>17; seed^=seed<<5; return (seed>>>0)/4294967296; }',
    '  for(let i=0;i<irLen;i++){',
    '    irData[i] = (nextRand()*2-1) * Math.exp(-decay*i/irLen);',
    '  }',
    '  const conv = ctx.createConvolver(); conv.buffer = irBuf;',
    '  const postGain = ctx.createGain(); postGain.gain.value = 0.3;',
    '  osc.connect(conv).connect(postGain).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: PeriodicWaveProbe =====
    'async function renderPeriodicWaveProbe(params){',
    '  const p = params.periodicWaveProbe;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const nH = p.numHarmonics||8;',
    '  const real = new Float32Array(nH+1); const imag = new Float32Array(nH+1);',
    '  real[0] = 0; imag[0] = 0;',
    '  for(let h=1;h<=nH;h++){',
    '    real[h] = +(p.realCoeffs[h-1]||0);',
    '    imag[h] = +(p.imagCoeffs[h-1]||0);',
    '  }',
    '  const wave = ctx.createPeriodicWave(real, imag, {disableNormalization:true});',
    '  const osc = ctx.createOscillator(); osc.setPeriodicWave(wave); osc.frequency.value = +p.fundamentalFreq;',
    '  const g = ctx.createGain(); g.gain.value = 0.3;',
    '  osc.connect(g).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: AnalyserProbe =====
    // Uses OfflineAudioContext + ScriptProcessorNode workaround to capture analyser data
    'async function renderAnalyserProbe(params){',
    '  const p = params.analyserProbe;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType; osc.frequency.value = +p.inputFreq;',
    '  // AnalyserNode doesn\'t work well with OfflineAudioContext in all browsers,',
    '  // so we route through a biquad with mild settings as a proxy for FFT-like processing',
    '  const filt = ctx.createBiquadFilter();',
    '  filt.type = "peaking"; filt.frequency.value = +p.inputFreq; filt.Q.value = 5.0; filt.gain.value = 6;',
    '  const filt2 = ctx.createBiquadFilter();',
    '  filt2.type = "highpass"; filt2.frequency.value = +p.inputFreq * 0.5; filt2.Q.value = 2.0;',
    '  osc.connect(filt).connect(filt2).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: ChannelMixProbe =====
    'async function renderChannelMixProbe(params){',
    '  const p = params.channelMixProbe;',
    '  // Render into a 2-channel context, split oscillators across left/right via',
    '  // ChannelMergerNode, then downmix to mono at destination (interchannelInterpretation="speakers")',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const merger = ctx.createChannelMerger(2);',
    '  merger.connect(ctx.destination);',
    '  for(let i=0;i<p.oscillators.length;i++){',
    '    const oc = p.oscillators[i];',
    '    const o = ctx.createOscillator(); o.type = oc.type; o.frequency.value = +oc.frequency;',
    '    const g = ctx.createGain(); g.gain.value = +oc.gain;',
    '    // Alternate oscillators between merger input 0 (left) and 1 (right)',
    '    o.connect(g).connect(merger, 0, i % 2);',
    '    o.start(0);',
    '  }',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Audio probe: StereoPannerProbe =====
    'async function renderStereoPannerProbe(params){',
    '  const p = params.stereoPannerProbe;',
    '  // 2-channel offline context for stereo panning, extract channel 0',
    '  const ctx = new OfflineAudioContext(2, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType; osc.frequency.value = +p.inputFreq;',
    '  const g = ctx.createGain(); g.gain.value = +p.gain;',
    '  const pan = ctx.createStereoPanner(); pan.pan.value = +p.pan;',
    '  osc.connect(g).connect(pan).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  // Return both channels concatenated for more signal',
    '  const ch0 = rendered.getChannelData(0);',
    '  const ch1 = rendered.getChannelData(1);',
    '  const combined = new Float32Array(ch0.length + ch1.length);',
    '  combined.set(ch0, 0); combined.set(ch1, ch0.length);',
    '  return combined;',
    '}',
    '',

    // ===== Audio probe: IIRFilterProbe =====
    'async function renderIirFilterProbe(params){',
    '  const p = params.iirFilterProbe;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType; osc.frequency.value = +p.inputFreq;',
    '  const preGain = ctx.createGain(); preGain.gain.value = +p.preGain;',
    '  const iir = ctx.createIIRFilter(new Float64Array(p.feedforward), new Float64Array(p.feedback));',
    '  const postGain = ctx.createGain(); postGain.gain.value = 0.3;',
    '  osc.connect(preGain).connect(iir).connect(postGain).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  const out = rendered.getChannelData(0);',
    '  // Clamp NaN/Infinity from unstable IIR coefficients',
    '  for(let i=0;i<out.length;i++){ if(!isFinite(out[i])) out[i]=0; }',
    '  return out;',
    '}',
    '',

    // ===== Audio probe: HRTFPannerProbe =====
    'async function renderHrtfPannerProbe(params){',
    '  const p = params.hrtfPannerProbe;',
    '  const ctx = new OfflineAudioContext(2, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType; osc.frequency.value = +p.inputFreq;',
    '  const g = ctx.createGain(); g.gain.value = +p.gain;',
    '  const panner = ctx.createPanner();',
    '  panner.panningModel = "HRTF";',
    '  panner.distanceModel = "inverse";',
    '  panner.positionX.value = +p.positionX;',
    '  panner.positionY.value = +p.positionY;',
    '  panner.positionZ.value = +p.positionZ;',
    '  osc.connect(g).connect(panner).connect(ctx.destination); osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  const ch0 = rendered.getChannelData(0);',
    '  const ch1 = rendered.getChannelData(1);',
    '  const combined = new Float32Array(ch0.length + ch1.length);',
    '  combined.set(ch0, 0); combined.set(ch1, ch0.length);',
    '  return combined;',
    '}',
    '',

    // ===== Audio probe: DelayProbe =====
    'async function renderDelayProbe(params){',
    '  const p = params.delayProbe;',
    '  const ctx = new OfflineAudioContext(1, BUFFER_LENGTH, SAMPLE_RATE);',
    '  const osc = ctx.createOscillator(); osc.type = p.inputType; osc.frequency.value = +p.inputFreq;',
    '  const dry = ctx.createGain(); dry.gain.value = +p.dryGain;',
    '  const wet = ctx.createGain(); wet.gain.value = +p.wetGain;',
    '  const delay = ctx.createDelay(0.1); delay.delayTime.value = +p.delayTime;',
    '  const fb = ctx.createGain(); fb.gain.value = +p.feedbackGain;',
    '  // Dry path',
    '  osc.connect(dry).connect(ctx.destination);',
    '  // Wet path with feedback loop',
    '  osc.connect(delay);',
    '  delay.connect(fb).connect(delay); // feedback loop',
    '  delay.connect(wet).connect(ctx.destination);',
    '  osc.start(0);',
    '  const rendered = await ctx.startRendering();',
    '  return rendered.getChannelData(0);',
    '}',
    '',

    // ===== Probe dispatch map =====
    'const PROBE_MAP = [',
    '  ["oscillatorMix", renderOscillatorMix],',
    '  ["biquadChain", renderBiquadChain],',
    '  ["compressorProbe", renderCompressorProbe],',
    '  ["waveShaperProbe", renderWaveShaperProbe],',
    '  ["convolverProbe", renderConvolverProbe],',
    '  ["periodicWaveProbe", renderPeriodicWaveProbe],',
    '  ["analyserProbe", renderAnalyserProbe],',
    '  ["channelMixProbe", renderChannelMixProbe],',
    '  ["stereoPannerProbe", renderStereoPannerProbe],',
    '  ["iirFilterProbe", renderIirFilterProbe],',
    '  ["hrtfPannerProbe", renderHrtfPannerProbe],',
    '  ["delayProbe", renderDelayProbe],',
    '];',
    '',

    // ===== Marker embedding =====
    'function embedMarker(f32, marker){',
    '  if(!marker) return f32;',
    '  const salt = (marker.salt|0)>>>0;',
    '  const val = +marker.value;',
    '  const D = marker.density||60;',
    '  const sIdx = marker.sIdx||0;',
    '  for(let i=0;i<f32.length;i++){',
    '    let seed = (((salt + sIdx*1315423911)|0) ^ (i*2654435761))|0;',
    '    const h = xorshift32(seed);',
    '    if((h%100)<D){',
    '      // Only embed on near-silent samples',
    '      if(Math.abs(f32[i]) < 0.01){',
    '        f32[i] = val;',
    '      }',
    '    }',
    '  }',
    '  return f32;',
    '}',
    '',

    // ===== Main: render all sessions and upload =====
    'export async function processAndSendAudioBATCH(postUrl){',
    '  const limiter = createAdaptiveLimiter({targetMs:1500});',
    '  const t0_all = performance.now();',
    '  let uploaded = 0, bytesUploaded = 0, failedBatches = 0;',
    '  let totalRenderMs = 0, totalUploadMs = 0;',
    '  const perKeyMs = {};',
    '  for(const [k] of PROBE_MAP) perKeyMs[k] = { renderMs:0, count:0 };',
    '  const uploadPromises = [];', // track every upload so we can await them all
    '',
    '  let stoppedEarly = false, stoppedAt = -1;',
    '  for(let si=0; si<SESS.length; si++){',
    '    // Soft deadline: audio.html sets window.__apStop at its 2-min timer.',
    '    // We check *before* starting each session so any in-flight probes',
    '    // finish their current render+upload naturally — no error thrown.',
    '    if (typeof window !== "undefined" && window.__apStop) {',
    '      stoppedEarly = true; stoppedAt = si;',
    '      console.log("[audio] soft-deadline stop at S"+(si+1)+"/"+SESS.length+"; finalizing");',
    '      break;',
    '    }',
    '    PLAN = SESS[si] || {};',
    '    const files = [], names = [];',
    '    const t0 = performance.now();',
    '',
    '    // Render all 12 audio probes for this session',
    '    // Per-probe timeout: some browsers (Safari/Firefox on low-end) can hang',
    '    // OfflineAudioContext.startRendering() indefinitely on malformed plans.',
    '    // Bail at 15s per probe so one stuck probe cannot pin the whole session.',
    '    for(let k=0; k<PROBE_MAP.length; k++){',
    '      const [keyName, renderFn] = PROBE_MAP[k];',
    '      try{',
    '        const tR0 = performance.now();',
    '        const renderPromise = renderFn(PLAN);',
    '        const timeoutP = new Promise((_, rej) => setTimeout(() => rej(new Error("probe timeout")), 15000));',
    '        let f32 = await Promise.race([renderPromise, timeoutP]);',
    '        const renderTime = performance.now() - tR0;',
    '        perKeyMs[keyName].renderMs += renderTime;',
    '        perKeyMs[keyName].count += 1;',
    '        totalRenderMs += renderTime;',
    '        // Embed freshness marker',
    '        const marker = PLAN[keyName] && PLAN[keyName]._marker;',
    '        if(marker) f32 = embedMarker(new Float32Array(f32), marker);',
    '        // Serialize Float32Array as raw binary',
    '        const u8 = new Uint8Array(f32.buffer, f32.byteOffset, f32.byteLength);',
    '        files.push(new Blob([u8], {type:"application/octet-stream"}));',
    '        names.push("S" + String(si+1) + "_audio_" + keyName + ".f32");',
    '        __progressTick({key:keyName,session:si+1,renderMs:renderTime});',
    '      }catch(e){ console.warn("[audio] render error "+keyName+" S"+(si+1), e); __progressTick({key:keyName,session:si+1,error:e.message}); }',
    '    }',
    '',
    '    const tRender = performance.now() - t0;',
    '',
    '    // Upload batch — track success/failure per batch',
    '    if(files.length > 0){',
    '      const batchBytes = files.reduce((s,b)=>s+b.size, 0);',
    '      const sessionIdx = si + 1;',
    '      const p = limiter.run(async()=>{',
    '        const fd = new FormData();',
    '        for(let i=0;i<files.length;i++) fd.append("bin", files[i], names[i]);',
    '        const u = postUrl + (postUrl.includes("?")?"&":"?") + "session="+sessionIdx;',
    '        const tU0 = performance.now();',
    '        // 45s per attempt × 4 attempts (1 initial + 3 retries, w/ backoff) = ~3min worst case',
    '        const resp = await __retry(()=>__fetchTimeout(u,{method:"POST",body:fd}, 45000), {retries:3,delay:400});',
    '        if(!resp || !resp.ok){ throw new Error("HTTP "+(resp&&resp.status)); }',
    '        const uploadTime = performance.now() - tU0;',
    '        totalUploadMs += uploadTime;',
    '        bytesUploaded += batchBytes;',
    '        console.log("[audio] S"+sessionIdx+" render="+tRender.toFixed(1)+"ms upload="+uploadTime.toFixed(1)+"ms keys="+files.length);',
    '        return { ok:true, sessionIdx };',
    '      }).then(r=>{ uploaded += 1; return r; }).catch(e=>{',
    '        failedBatches += 1;',
    '        console.warn("[audio] upload err S"+sessionIdx, e);',
    '        return { ok:false, sessionIdx, error:String(e && e.message || e) };',
    '      });',
    '      uploadPromises.push(p);',
    '    }',
    '  }',
    '',
    '  // Wait for every tracked upload — not just whatever is inflight at this moment',
    '  const uploadResults = await Promise.all(uploadPromises);',
    '  const t1_all = performance.now();',
    '  const totalMs = t1_all - t0_all;',
    '  // Compute per-key averages',
    '  const perKeyAvg = {};',
    '  for(const [k,v] of Object.entries(perKeyMs)){ perKeyAvg[k] = v.count ? +(v.renderMs/v.count).toFixed(2) : 0; }',
    '  const sessionsAttempted = stoppedEarly ? stoppedAt : SESS.length;',
    '  console.log("[audio] done sessions="+sessionsAttempted+"/"+SESS.length+" stoppedEarly="+stoppedEarly+" time="+totalMs.toFixed(1)+"ms render="+totalRenderMs.toFixed(1)+"ms upload="+totalUploadMs.toFixed(1)+"ms bytes="+bytesUploaded+" uploaded="+uploaded+" failed="+failedBatches);',
    '  return { sessions: sessionsAttempted, sessionsPlanned: SESS.length, stoppedEarly, timeMs: totalMs, uploaded, failedBatches, renderMs: totalRenderMs, uploadMs: totalUploadMs, bytesUploaded: bytesUploaded, perKeyMs: perKeyAvg, uploadResults };',
    '}',
  ];

  return js.join('\n');
}

module.exports = { buildAudioFrozenBundle };
