'use strict';

/**
 * Build a one-shot ESM bundle (no template-backtick pollution; uploads as Blob PNG).
 */
function buildFrozenBundle(input) {
  const W = (input.width | 0) || 100;
  const H = (input.height | 0) || 100;

  // Accept a single plan as well as sessions=[...].
  const SESS = Array.isArray(input.sessions)
    ? input.sessions
    : (input.plan ? [input.plan] : []);

  const NUM_SUB = input.numSubSessions != null
    ? Number(input.numSubSessions)
    : (SESS.length > 0 ? SESS.length : 1);

  const js = [
    '/* ===== LearnedFP Frozen (blob-only) ===== */',
    `const CANVAS_WIDTH=${W}, CANVAS_HEIGHT=${H};`,
    `const SESS=${JSON.stringify(SESS || [{}])};`,
    `const NUM_SUB=${Math.max(1, NUM_SUB)};`,
    'let PLAN = SESS[0] || {};',

    // ---------- runtime helpers ----------
    'let HEADLESS = true;',
    'const __isEmojiType = (t)=> t==="faces"||t==="persons"||t==="travel"||t==="hands";',
    'const __skipPNG = (t)=> t === "randomFont" || __isEmojiType(t);',  
    '(function ensureRoot(){',
    '  if (HEADLESS) return;',
    '  let r = document.getElementById("canvas-root");',
    '  if(!r){ r=document.createElement("div"); r.id="canvas-root";',
    '    r.style.display="flex"; r.style.flexWrap="wrap"; r.style.gap="8px"; r.style.maxWidth="840px";',
    '    document.body.appendChild(r); }',
    '})();',

    'const __root = document.getElementById("canvas-root");',
    // === progress event (works in headless & dom) ===
    'function __progressTick(){ try{ self.dispatchEvent(new CustomEvent("pp:canvas")); }catch(e){} }',
    'function createCanvas(name,type){',
    '  if(name===undefined) name=""; if(type===undefined) type="2d";',
    '  // HEADLESS: do not attach to DOM; reuse a single global 3D canvas to keep one WebGL context.',
    '  if (HEADLESS) {',
    '    if (type === "3d") {',
    '      if (!globalThis.__pp_shared3d) {',
    '        const cv = document.createElement("canvas");',
    '        cv.width = CANVAS_WIDTH; cv.height = CANVAS_HEIGHT;',
    '        globalThis.__pp_shared3d = cv;',
    '      }',
    '      return globalThis.__pp_shared3d;',
    '    }',
    '    const cv=document.createElement("canvas");',
    '    cv.width=CANVAS_WIDTH; cv.height=CANVAS_HEIGHT;',
    '    return cv.getContext("2d",{willReadFrequently:true});',
    '  }',
    '  const box=document.createElement("div"); box.className="pp-canvas-item";',
    '  box.style.display="inline-flex"; box.style.flexDirection="column"; box.style.alignItems="center"; box.style.margin="6px";',
    '  const cv=document.createElement("canvas"); cv.width=CANVAS_WIDTH; cv.height=CANVAS_HEIGHT;',
    '  const lb=document.createElement("div"); lb.className="pp-label"; lb.textContent=String(name); lb.style.marginTop="4px"; lb.style.fontSize="12px"; lb.style.color="#333";',
    '  box.appendChild(cv); box.appendChild(lb); __root.appendChild(box);',
    '  return type==="3d"?cv:cv.getContext("2d",{willReadFrequently:true});',
    '}',

    // ===== Pre-upload pixel cache: stash the raw RGBA for emoji categories only. =====
    'const __prePixels = new Map();',
    'function __registerPrePixels(name, u8){ try{ if(name&&u8) __prePixels.set(String(name), u8); }catch(e){} }',

    // ===== Adaptive concurrency limiter =====
    'function createAdaptiveLimiter(opts = {}){',
    '  const cores = (globalThis.navigator?.hardwareConcurrency || 4);',
    '  const conf = {',
    '    min: 2,',
    '    max: Math.min(12, cores),',
    '    start: Math.min(6, cores),',
    '    targetMs: opts.targetMs ?? 900,',
    '    smooth: 0.2,',
    '    upStep: 1,',
    '    downStep: 1',
    '  };',
    '  let limit = conf.start;',
    '  const inflight = new Set();',
    '  let ema = null;',
    '  let winCnt = 0, failCnt = 0;',
    '  const winSize = () => Math.max(8, limit * 2);',
    '  function _feedback(ok, ms){',
    '    ema = (ema == null) ? ms : ema * (1 - conf.smooth) + ms * conf.smooth;',
    '    winCnt += 1; if (!ok) failCnt += 1;',
    '    if (winCnt >= winSize()){',
    '      const fr = failCnt / winCnt;',
    '      if (fr > 0.15){',
    '        limit = Math.max(conf.min, limit - conf.downStep);',
    '      } else {',
    '        if (ema < conf.targetMs && limit < conf.max){',
    '          limit = limit + conf.upStep;',
    '        } else if (ema > conf.targetMs * 1.6){',
    '          limit = Math.max(conf.min, limit - conf.downStep);',
    '        }',
    '      }',
    '      winCnt = 0; failCnt = 0;',
    '    }',
    '  }',
    '  async function run(task){',
    '    while (inflight.size >= limit){ try { await Promise.race(inflight); } catch{} }',
    '    const p = (async()=>{',
    '      const t0 = performance.now();',
    '      try { const r = await task(); _feedback(true, performance.now()-t0); return r; }',
    '      catch(e){ _feedback(false, performance.now()-t0); throw e; }',
    '    })();',
    '    inflight.add(p); p.finally(()=>inflight.delete(p));',
    '    return p;',
    '  }',
    '  function waitAll(){ return Promise.allSettled([...inflight]); }',
    '  return { run, waitAll, get limit(){return limit;}, get ema(){return ema;} };',
    '}',


    '// --- fire and forget log sender ---',
'function __sendLog(postUrl, payloadObj){',
'  try{',
'    const u = postUrl + (postUrl.includes("?") ? "&" : "?") + "kind=log";',
'    const body = JSON.stringify(payloadObj);',
'    if (globalThis.navigator && typeof globalThis.navigator.sendBeacon === "function"){',
'      const blob = new Blob([body], { type: "application/json" });',
'      globalThis.navigator.sendBeacon(u, blob);',
'      return;',
'    }',
'    fetch(u, {',
'      method: "POST",',
'      headers: { "Content-Type": "application/json" },',
'      body: body,',
'      keepalive: true',
'    }).catch(()=>{});',
'  }catch(e){}',
'}',


    // a-randomString
    'export function arandomString(){',
    '  const c = (PLAN && PLAN["a-randomString"]) || { color:[0,0,0,0.65], lines:["","","","",""] };',
    '  const ctx = createCanvas("a-randomString"); ctx.textBaseline="alphabetic";',
    '  ctx.fillStyle = "rgba("+c.color[0]+","+c.color[1]+","+c.color[2]+","+c.color[3]+")";',
    '  const L = c.lines || [];',
    '  const fonts = ["serif","sans-serif","monospace","cursive","fantasy"];',
    '  for(let r=0;r<5;r++){ ctx.font="15px "+fonts[r]; ctx.fillText(String(L[r]||""),0,15+20*r); }',
    '  return ctx;',
    '}',

    // randomFont (null-guard + background pixel watermark + ORI cache)
    'export function randomFont(name){',
    '  const c = (PLAN && PLAN.randomFont) || { fill:"rgba(0,0,0,1)", items:[], brightnessShift:0, maskSalt:0 };',
    '  const ctx = createCanvas("randomFont");',
    '  ctx.clearRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT); ctx.textAlign="left"; ctx.textBaseline="alphabetic";',
    '  ctx.fillStyle=String(c.fill||"rgba(0,0,0,1)");',
    '  for(const raw of (c.items||[])){',
    '    const it = (raw && typeof raw==="object") ? raw : {};',
    '    const size = Number(it.size) || 12;',
    '    const font = String(it.font || "Arial");',
    '    const text = String(it.text || "");',
    '    const x = Number(it.x) || 0;',
    '    const y = Number(it.y) || 0;',
    '    ctx.font = String(size) + "px " + font;',
    '    ctx.fillText(text, x, y);',
    '  }',
    '  // === Background pixel watermark: write (code,code,code,0) only on A==0 R==G==B pixels ===',
    '  try{',
    '    const img = ctx.getImageData(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);',
    '    const d = img.data;',
    '    // Unify: code is bs (clamped to 1..254).',
    '    let code = ((c.bs ?? c.bsCode ?? c.brightnessShift) | 0);',
    '    if (code < 1) code = 1; else if (code > 254) code = 254;',
    '    const bsRaw = code;',  // Seed still encodes bs so positions are reproducible.',
    '    const salt  = ((c.maskSalt|0)>>>0);',
    '    let sIdx = 0; try{ const m = String(name||"").match(/^S(\\d+)_/); if(m) sIdx = (m[1]|0); }catch{}',
    '    function xorshift32(u){ u|=0; u^=u<<13; u^=u>>>17; u^=u<<5; return u>>>0; }',
    '    const D = Number(c.D) || 80;',
    '    for (let p=0; p<d.length; p+=4){',
    '      const a0=d[p+3]; if (a0!==0) continue;',            // Background pixels only.',
    '      const idx=(p>>2); const y=(idx / CANVAS_WIDTH) | 0; const x=idx - y*CANVAS_WIDTH;',
    '      let seed = (((salt + bsRaw + (sIdx*1315423911))|0) ^ ((y<<16)|x))|0;',
    '      const h = xorshift32(seed);',
    '      if ((h % 100) < D) { d[p]=code; d[p+1]=code; d[p+2]=code; d[p+3]=0; }',
    '    }',
    '    ctx.putImageData(img,0,0);',
    '    // Cache ORI pixels for the ori_* upload.',
    '    const u8 = new Uint8Array(img.data.buffer.slice(0));',
    '    const nameKey = name || "randomFont";',
    '    __registerPrePixels(nameKey, u8);',
    '  }catch(e){ console.warn("[randomFont watermark/prePixels]", e); }',
        '  return ctx;',
    '}',


    // ===== emoji: apply bs and cache pre-upload pixels =====
    '// emoji',
    'export function drawEmoji(category, name){',
    '  const cfg = (PLAN && PLAN[category]) || { items:[], brightnessShift:0 };',
    '  const ctx = createCanvas(String(category));',
    '  ctx.clearRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);',
    '',
    '  const gridSize = 6;',
    '  const cellSize = CANVAS_WIDTH / gridSize;',
    '  let k = 0;',
    '',
    '  const items = (cfg.items || []).slice(0, 36);',
    '',
    '  for (let row = 0; row < gridSize; row++) {',
    '    for (let col = 0; col < gridSize; col++) {',
    '      if (k >= items.length) break;',
    '',
    '      const raw = items[k++];',
    '      const it = (raw && typeof raw === "object") ? raw : {};',
    '',
    '      const add = Number(it.fontSize) || 0;',
    '      const fontSize = +(((CANVAS_WIDTH / 6) * 0.6) + add).toFixed(3);',
    '      const fontStr = String(fontSize.toFixed(3) + "px Arial");',
    '',
    '      let ch = "";',
    '      if (it.ch != null) {',
    '        ch = String(it.ch);',
    '      } else if (Number.isInteger(it.cp) && Number.isInteger(it.cp2)) {',
    '        ch = String.fromCodePoint(it.cp, it.cp2);',
    '      } else if (Number.isInteger(it.cp)) {',
    '        ch = String.fromCodePoint(it.cp);',
    '      } else {',
    '        ch = "\\u25A1";',
    '      }',
    '',
    '      const dx = Number(it.dx) || 0;',
    '      const dy = Number(it.dy) || 0;',
    '      const rot = Number(it.rot) || 0;',
    '',
    '      const x = col * cellSize + dx;',
    '      const y = row * cellSize + fontSize + dy;',
    '',
    '      ctx.save();',
    '      ctx.font = fontStr;',
    '      ctx.translate(x + fontSize / 2, y - fontSize / 2);',
    '      ctx.rotate(rot);',
    '      ctx.fillText(ch, -fontSize / 2, fontSize / 2);',
    '      ctx.restore();',
    '    }',
    '  }',
    '',
    '  // === Background pixel watermark: write (code,code,code,0) only on A==0 pixels ===',
  '  try {',
  '    const img = ctx.getImageData(0, 0, CANVAS_WIDTH, CANVAS_HEIGHT);',
  '    const d = img.data;',
  '    // Unify: code is bs (clamped to 1..254).',
  '    let code = ((cfg.bs ?? cfg.bsCode ?? cfg.brightnessShift) | 0);',
  '    if (code < 1) code = 1; else if (code > 254) code = 254;',
  '    const bsRaw = code;',
  '    const salt  = ((cfg.maskSalt|0)>>>0);',
  '    const D     = Number(cfg.D) || 80;',
  '    let sIdx    = 0;',
  '    if (Number.isFinite(cfg.sIdx) && cfg.sIdx > 0) {',
  '      sIdx = cfg.sIdx|0;',
  '    } else {',
  '      try { const m = String(name||"").match(/^S(\\d+)_/); if (m) sIdx = (m[1]|0); } catch {}',
  '    }',
  '    function xorshift32(u){ u|=0; u^=u<<13; u^=u>>>17; u^=u<<5; return u>>>0; }',
  '    for (let p = 0; p < d.length; p += 4) {',
  '      const a0 = d[p+3];',
  '      if (a0 !== 0) continue;',  
  '      // Optional: only write when the background gray is consistent — uncomment the next two lines to enable.',
  '      // const r0=d[p], g0=d[p+1], b0=d[p+2];',
  '      // if (r0!==g0 || g0!==b0) continue;',
  '      const idx = (p>>2);',
  '      const y = (idx / CANVAS_WIDTH) | 0;',
  '      const x = idx - y * CANVAS_WIDTH;',
  '      let seed = (((salt + bsRaw + (sIdx*1315423911))|0) ^ ((y<<16)|x))|0;',
  '      const h = xorshift32(seed);',
  '      if ((h % 100) < D) {',
  '        d[p]   = code; d[p+1] = code; d[p+2] = code; d[p+3] = 0;',
  '      }',
  '    }',
  '    ctx.putImageData(img, 0, 0);',
  '    // Cache ORI pixels for the raw .rgba upload.',
  '    const u8 = new Uint8Array(img.data.buffer.slice(0));',
  '    const nameKey = name || String(category);',
  '    __registerPrePixels(nameKey, u8);',
  '  } catch(e) { console.warn("[emoji watermark/prePixels]", e); }',
    '',
    '  return ctx;',
    '}',

    // moire
    'export function drawMoirePatternWatermarked(){',
    '  const c = (PLAN && PLAN.moire) || { spacing:4.5, angle1:0.1, angle2:0.15, lw1:1, lw2:1, alpha1:0.4, alpha2:0.4, phase:0, freq:1.6 };',
    '  const ctx=createCanvas("moire"); ctx.clearRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);',
    '  const {spacing, angle1, angle2, lw1, lw2, alpha1, alpha2, phase, freq} = c;',
    '  ctx.globalCompositeOperation="multiply"; ctx.imageSmoothingEnabled=true;',
    '  const g1=ctx.createLinearGradient(0,0,CANVAS_WIDTH,0); g1.addColorStop(0,"rgba(0,0,0,1)"); g1.addColorStop(1,"rgba(60,60,60,1)");',
    '  const g2=ctx.createLinearGradient(0,0,0,CANVAS_HEIGHT); g2.addColorStop(0,"rgba(0,0,0,1)"); g2.addColorStop(1,"rgba(60,60,60,1)");',
    '  ctx.save(); ctx.translate(CANVAS_WIDTH*0.5,CANVAS_HEIGHT*0.5); ctx.rotate(+angle1||0); ctx.translate(-CANVAS_WIDTH*0.5,-CANVAS_HEIGHT*0.5); ctx.strokeStyle=g1; ctx.globalAlpha=+alpha1||0.4; ctx.lineWidth=+lw1||1;',
    '  for(let y=-CANVAS_HEIGHT; y<CANVAS_HEIGHT*2; y+=(+spacing||4.5)){ const wy=(Math.abs(y)%((+spacing||4.5)*4)<(+spacing||4.5)? (0.6*Math.sin((+freq||1.6)*y + (+phase||0))) : 0); ctx.beginPath(); ctx.moveTo(-CANVAS_WIDTH,y+wy); ctx.lineTo(CANVAS_WIDTH*2,y+wy); ctx.stroke(); }',
    '  ctx.restore();',
    '  ctx.save(); ctx.translate(CANVAS_WIDTH*0.5,CANVAS_HEIGHT*0.5); ctx.rotate(+angle2||0); ctx.translate(-CANVAS_WIDTH*0.5,-CANVAS_HEIGHT*0.5); ctx.strokeStyle=g2; ctx.globalAlpha=+alpha2||0.4; ctx.lineWidth=+lw2||1;',
    '  for(let y2=-CANVAS_HEIGHT; y2<CANVAS_HEIGHT*2; y2+=(+spacing||4.5)){ const wy2=(Math.abs(y2)%((+spacing||4.5)*5)<(+spacing||4.5)? (0.6*Math.sin((+freq||1.6)*0.8*y2 + (+phase||0) + 0.7)) : 0); ctx.beginPath(); ctx.moveTo(-CANVAS_WIDTH,y2+wy2); ctx.lineTo(CANVAS_WIDTH*2,y2+wy2); ctx.stroke(); }',
    '  ctx.restore();',
    '  ctx.save(); ctx.globalCompositeOperation="source-over"; ctx.shadowColor="rgba(0,0,0,0.08)"; ctx.shadowBlur=0.8; ctx.globalAlpha=1.0; ctx.drawImage(ctx.canvas,0,0); ctx.restore();',
    '  return ctx;',
    '}',

   
    // gradQuantSteps
    'export function gradQuantSteps(){',
    '  const c = (PLAN && PLAN["gradQuantSteps"]) || { angle: 0.0, stops: [0,1], noiseMod: 13, noiseAmp: 1 };',
    '  const ctx = createCanvas("gradQuantSteps");',
    '  const w = ctx.canvas.width, h = ctx.canvas.height; ctx.clearRect(0,0,w,h);',
    '  const a = +c.angle||0, cx=w/2, cy=h/2, R=Math.hypot(w,h);',
    '  const x0=cx-Math.cos(a)*R, y0=cy-Math.sin(a)*R, x1=cx+Math.cos(a)*R, y1=cy+Math.sin(a)*R;',
    '  const g = ctx.createLinearGradient(x0,y0,x1,y1);',
    '  const stops = Array.isArray(c.stops)&&c.stops.length?c.stops:[0,1];',
    '  for(let k=0;k<stops.length;k++){',
    '    const t = Math.max(0, Math.min(1, +stops[k])); const v = Math.round(t*255);',
    '    g.addColorStop(t, `rgb(${v},${v},${v})`);',
    '  }',
    '  ctx.fillStyle = g; ctx.fillRect(0,0,w,h);',
    '  const amp=+c.noiseAmp||0, mod=Math.max(3, +c.noiseMod|0);',
    '  if(amp>0){',
    '    const img = ctx.getImageData(0,0,w,h); const d=img.data;',
    '    for(let i=0;i<d.length;i+=4){ if(((i>>2)%mod)===0){ d[i]+=amp; d[i+1]+=amp; d[i+2]+=amp; } }',
    '    ctx.putImageData(img,0,0);',
    '  }',
    '  return ctx;',
    '}',

    // shadowBlurProbe
    'export function shadowBlurProbe(){',
    '  const c = (PLAN && PLAN["shadowBlurProbe"]) || {',
    '    count: 4, gco: "multiply",',
    '    shapePool: ["circle","rect","diamond"],',
    '    blurMax: 16.0,',
    '    colors: ["rgba(0,0,0,0.6)","rgba(0,0,0,0.4)","rgba(20,0,60,0.4)","rgba(0,40,80,0.4)"]',
    '  };',
    '  const ctx = createCanvas("shadowBlurProbe");',
    '  const w = ctx.canvas.width, h = ctx.canvas.height;',
    '  ctx.clearRect(0,0,w,h);',
    '  ctx.globalCompositeOperation = String(c.gco||"source-over");',
    '  const N = Math.max(1, (+c.count|0));',
    '  const pool = Array.isArray(c.shapePool)&&c.shapePool.length?c.shapePool:["circle"];',
    '  const colors = Array.isArray(c.colors)&&c.colors.length?c.colors:["rgba(0,0,0,0.5)"];',
    '  for(let i=0;i<N;i++){',
    '    ctx.save();',
    '    ctx.shadowColor = String(colors[i % colors.length]);',
    '    ctx.shadowBlur = Math.max(0, +c.blurMax||0) * Math.random();',
    '    ctx.fillStyle = "#000";',
    '    const x = 0.05*w + Math.random()*0.90*w;',
    '    const y = 0.05*h + Math.random()*0.90*h;',
    '    const size = Math.min(w,h) * (0.12 + 0.18*Math.random());',
    '    const shape = String(pool[i % pool.length]);',
    '    ctx.beginPath();',
    '    if(shape==="circle"){ ctx.arc(x,y,size,0,Math.PI*2); }',
    '    else if(shape==="rect"){ ctx.rect(x-size,y-size,size*2,size*2); }',
    '    else { ctx.moveTo(x, y-size); ctx.lineTo(x+size, y); ctx.lineTo(x, y+size); ctx.lineTo(x-size, y); ctx.closePath(); }',
    '    ctx.fill();',
    '    ctx.restore();',
    '  }',
    '  ctx.globalCompositeOperation = "source-over";',
    '  return ctx;',
    '}',

    // utils: toBlob + upload
    'function __toBlob(cv){ return new Promise((resolve,reject)=>{',
    '  try{',
    '    if (cv && typeof cv.convertToBlob === "function"){',
    '      cv.convertToBlob({type:"image/png"}).then(resolve, reject);',
    '    } else if (cv && typeof cv.toBlob === "function"){',
    '      cv.toBlob(b => b ? resolve(b) : reject(new Error("toBlob returned null")), "image/png");',
    '    } else {',
    '      reject(new Error("no toBlob/convertToBlob on canvas"));',
    '    }',
    '  }catch(e){ reject(e); }',
    '}); }',

    '',
    '// --- tiny retry helper (for draw/upload robustness) ---',
    'async function __retry(fn, opts={}){',
    '  const retries = Number.isFinite(opts.retries)? opts.retries : 2;',
    '  const delay   = Number.isFinite(opts.delay)?   opts.delay   : 120;',
    '  let lastErr;',
    '  for (let i=0;i<=retries;i++){',
    '    try { return await fn(); }',
    '    catch(e){ lastErr=e; if(i<retries){ await new Promise(r=>setTimeout(r, delay)); } }',
    '  }',
    '  throw lastErr;',
    '}',
    '',



    'async function __postPNG(postUrl, key, blob){',
    '  const u = postUrl + (postUrl.includes("?") ? "&" : "?") + "key=" + encodeURIComponent(key) + "&src=webglbatch";',
    '  const resp = await fetch(u, { method:"POST", headers:{ "Content-Type":"image/png" }, body: blob });',
    '  if(!resp.ok) throw new Error("upload "+key+" status "+resp.status);',
    '  return resp;',
    '}',

    // ---------- Blob PNG upload only + (optional) client-side pixel hash ----------
    'async function __sha256Hex(u8){',
    '  try {',
    '    if (globalThis.isSecureContext && globalThis.crypto && globalThis.crypto.subtle) {',
    '      const buf = await globalThis.crypto.subtle.digest("SHA-256", u8);',
    '      return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,"0")).join("");',
    '    }',
    '  } catch (e) {',
    '    console.warn("[sha256] subtle digest failed:", e);',
    '  }',
    '  return null;',
    '}',

    'const TYPE_MAP = [',
    '  "faces","persons","travel","hands",',
    '  "randomFont","moire",',
    '  "a-randomString",',
    '  "gradQuantSteps","shadowBlurProbe",',
    '];',

    // Dispatcher (passes name into drawEmoji so we can cache ORI pixels per draw).
    'function drawOne(type, name){',
    '  switch(type){',
    '    case "faces": case "persons": case "travel": case "hands":',
    '      return drawEmoji(type, name);',
    '    case "randomFont":   return randomFont(name);',
    '    case "moire":        return drawMoirePatternWatermarked();',
    '    case "a-randomString": return arandomString();',
    '    case "gradQuantSteps":        return gradQuantSteps();',
    '    case "shadowBlurProbe":       return shadowBlurProbe();',
    '    default: return null;',
    '  }',
    '}',

        'export async function processAndSendCanvasDataBATCH(postUrl){',
    '  const BATCH_DRAW = 3;',
    '  const limiter = createAdaptiveLimiter({ targetMs: 900 });',
    '  const t0_all = performance.now();',
    '  let uploaded = 0, bytesTotal = 0, sessions = 0;',
    '  let totalRenderMs = 0, totalUploadMs = 0;',
    '',
    '  for (let si = 0; si < SESS.length; si++) {',
    '    PLAN = SESS[si] || {};',
    '    const files = [], names = [];',
    '    const oriFiles = [], oriNames = [];',
    '    const t0 = performance.now();',
    '',
    '    // 1) Render every key for the current session into memory.',
    '    for (let k = 0; k < TYPE_MAP.length; k++) {',
    '      const type = TYPE_MAP[k];',
    '      const name = "S" + String(si + 1) + "_" + type + "_" + String(k + 1);',
    '      const ctx  = drawOne(type, name);',
    '      const canvas = (ctx && ctx.canvas) ? ctx.canvas : ctx;',
    '      if (!canvas || typeof canvas.toBlob !== "function") {',
    '        console.warn("blob: invalid " + name);',
    '        continue;',
    '      }',
    '      // Collect the raw RGBA for emoji / randomFont keys.',
    ' if (__skipPNG(type)) {',
    '        const u8 = __prePixels.get(name) || __prePixels.get(type) || null;',
    '        if (u8 && u8.byteLength) {',
    '          oriFiles.push(new Blob([u8.buffer], {type:"application/octet-stream"}));',
    '          oriNames.push(name.replace(/^S(\\d+)_/, "S$1_raw_") + ".rgba");',
    '          __progressTick();',
    '        }',
    '      }',
    '      if (!__skipPNG(type)) {',
    '        const blob = await __retry(() => __toBlob(canvas), { retries: 2, delay: 120 });',
    '        files.push(blob);',
    '        names.push(name + ".png");',
    '        __progressTick();',
    '      } else {',
    '        // skip PNG',
    '      }',

    '       if (((k + 1) % BATCH_DRAW) === 0) await new Promise(r => setTimeout(r, 0));',
    '    }',
    '',
    '    const tRender = performance.now() - t0;',
    '    totalRenderMs += tRender;',
    '    sessions++;',
    '',
    '    // 2) Concurrent upload (adaptive rate limiting).',
    '    limiter.run(async () => {',
    '      // 2.1 Send ORI first (if any).',
    '      if (oriFiles.length){',
    '        const fdOri = new FormData();',
    '        for (let i = 0; i < oriFiles.length; i++) fdOri.append("bin", oriFiles[i], oriNames[i]);',
    '        const uOri = postUrl + (postUrl.includes("?") ? "&" : "?") + "session=" + (si + 1) + "&kind=raw";',
    
    '        try {',
    '          await __retry(() => fetch(uOri, { method: "POST", body: fdOri }), { retries: 2, delay: 180 });',
    '        } catch(e){ console.warn("[batch ori] upload err S"+(si+1), e); }',

    '      }',
    '      // 2.2 Then send the PNG batch.',
    '      const fd = new FormData();',
    '      for (let i = 0; i < files.length; i++) fd.append("img", files[i], names[i]);',
    '      const u = postUrl + (postUrl.includes("?") ? "&" : "?") + "session=" + (si + 1);',
    '      const tU0 = performance.now();',
    '      const resp = await __retry(() => fetch(u, { method: "POST", body: fd }), { retries: 2, delay: 200 });',
    '      const tU1 = performance.now();',
    '      totalUploadMs += (tU1 - tU0);',
    '      const xbytes = Number(resp.headers.get("X-Received-Bytes") || 0);',
    '      if (!resp.ok) console.warn("[batch] upload failed for session", si+1, resp.status);',
    '      uploaded += 1; bytesTotal += xbytes;',
    '      const line = `[batch] S${si+1} render=${tRender.toFixed(1)}ms upload=${(tU1 - tU0).toFixed(1)}ms received=${xbytes||"?"}`;',
'      console.log(line);',
'      __sendLog(postUrl, {',
'        kind: "batch_line",',
'        session: si + 1,',
'        render_ms: +tRender.toFixed(1),',
'        upload_ms: +(tU1 - tU0).toFixed(1),',
'        received_bytes: xbytes || null,',
'        line: line,',
'        ts: Date.now()',
'      });',
    '    });',
    '  }',
    '',

    '  await limiter.waitAll();',
    '  const t1_all = performance.now();',
    '  const summary = `[batch] render+upload sessions=${sessions} time=${(t1_all - t0_all).toFixed(1)}ms bytes=${bytesTotal} conc=${limiter.limit} ema=${(limiter.ema??0).toFixed(1)}ms`;',
'  console.log(summary);',
'  __sendLog(postUrl, {',
'    kind: "batch_summary",',
'    sessions: sessions,',
'    total_ms: +(t1_all - t0_all).toFixed(1),',
'    bytes: bytesTotal,',
'    conc: limiter.limit,',
'    ema_ms: +(limiter.ema ?? 0).toFixed(1),',
'    line: summary,',
'    ts: Date.now()',
'  });',
'  return {',
'    sessions,',
'    uploaded,',
'    bytesTotal,',
'    renderMs: +totalRenderMs.toFixed(1),',
'    uploadMs: +totalUploadMs.toFixed(1),',
'    totalMs: +(t1_all - t0_all).toFixed(1),',
'  };',
    '}',


    // Default export (so callers can do `import * as mod from ...`).
    'export default {',
    '  arandomString,',
    '  randomFont, drawMoirePatternWatermarked, drawEmoji,',
    '  gradQuantSteps, shadowBlurProbe,',
    '  processAndSendCanvasDataBATCH',
    '};'
  ].join('\n');

  return js;
}

module.exports = { buildFrozenBundle };
